import { ResearchProfile } from "./types";

export const PRESET_SWT302: ResearchProfile = {
  id: "preset_swt302",
  name: "SWT302 REST API EP/BVA",
  description:
    "Nghiên cứu sinh ca kiểm thử tự động cho REST API bằng Phân hoạch tương đương (EP) và Phân tích giá trị biên (BVA) theo chuẩn RBL môn SWT302.",
  researchQuestions: [
    "RQ FA26-EXT-12: Kỹ thuật kiểm thử black-box nào dựa trên EP và BVA cho tham số HTTP request của REST API?",
    "Các nghiên cứu thực nghiệm định lượng kết quả phát hiện lỗi / coverage như thế nào trong Table/Figure?",
  ],
  reviewType: "systematic_review",
  searchStrings: [
    {
      id: "swt302_str_a",
      name: "String A (Chính thức theo protocol)",
      query:
        '("REST API testing" OR "natural language requirement" OR "RESTestBench") AND ("equivalence partitioning" OR "boundary-value analysis" OR "boundary testing") AND ("fault detection" OR "mutant detection" OR "bugs found")',
      isDefault: true,
      source: "google_scholar",
    },
    {
      id: "swt302_str_b",
      name: "String B (Dự phòng mở rộng)",
      query:
        '("REST API" OR "RESTful") AND ("black-box testing" OR "boundary value" OR "equivalence partition") AND ("automated testing" OR "test generation")',
      isDefault: false,
      source: "google_scholar",
    },
  ],
  yearRange: {
    start: 2020,
    end: 2026,
    enabled: true,
  },
  languageRequirements: ["English", "en"],
  allowedPublicationTypes: ["conference", "journal", "proceedings"],
  minPageCount: 4,
  targetIncludedCount: 15,
  sourcePolicies: {
    google_scholar: {
      prismaRole: "supplementary",
      notes:
        "Nguồn Google Scholar chỉ là paper ứng viên bổ trợ, không tính trực tiếp vào Identification của sơ đồ PRISMA chính thống.",
    },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "supplementary" },
    semantic_scholar: { prismaRole: "supplementary" },
  },
  criteria: [
    {
      id: "IC-L",
      label: "Ngôn ngữ tiếng Anh",
      description: "Paper viết bằng tiếng Anh và có bằng chứng văn bản.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "language",
      parameters: { allowedLanguages: ["English", "en"] },
    },
    {
      id: "IC-T",
      label: "Hội nghị / Tạp chí khoa học",
      description: "Đăng trên conference hoặc journal khoa học (loại trừ thesis, dissertation, blog).",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["conference", "journal", "proceedings", "symposium", "workshop"],
        rejectTheses: true,
        rejectPreprints: false,
      },
    },
    {
      id: "IC-Y",
      label: "Năm xuất bản 2020 - 2026",
      description: "Xuất bản trong khung năm 2020 đến 2026 theo protocol SWT302.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "year_range",
      parameters: { startYear: 2020, endYear: 2026 },
    },
    {
      id: "IC-P",
      label: "Kiểm thử REST API mức HTTP request",
      description:
        "Kiểm thử ở mức request cho dịch vụ HTTP (yêu cầu NL và/hoặc schema API: OpenAPI, Swagger, RAML). GraphQL riêng lẻ không đạt.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "swt302_ep_bva",
      parameters: { checkScope: "rest_api" },
    },
    {
      id: "IC-I",
      label: "Kỹ thuật EP và/hoặc BVA cho tham số request",
      description:
        "Kỹ thuật thiết kế test black-box: Phân hoạch tương đương (EP) và/hoặc Phân tích giá trị biên (BVA) cho tham số request.",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "swt302_ep_bva",
      parameters: { checkTechnique: "ep_bva" },
      evidenceRequirements: "Cần trích dẫn đoạn văn bản mô tả phương pháp EP/BVA cho tham số request (trang, mục).",
    },
    {
      id: "IC-E",
      label: "Kết quả thực nghiệm định lượng trong Table/Figure",
      description:
        "Có ít nhất 1 con số kết quả thực nghiệm trong Table hoặc Figure (không chỉ nhắc metric trong text).",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "swt302_ep_bva",
      parameters: { checkEmpirical: "table_or_figure" },
      evidenceRequirements: "Cần số liệu định lượng (%, số lỗi, coverage...) gắn liền với Table hoặc Figure.",
    },
    {
      id: "EC-D",
      label: "Trùng lặp với bài báo đã có (Duplicate)",
      description: "Trùng khóa chính DOI hoặc trùng tiêu đề đã xác nhận.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "EC-S",
      label: "Dưới 4 trang (Short paper / Poster)",
      description: "Loại bài báo dưới 4 trang khi đã xác minh số trang từ toàn văn.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "page_count",
      parameters: { minPages: 4 },
    },
    {
      id: "EC-A",
      label: "Không thể truy cập toàn văn (Unreachable full-text)",
      description: "Chỉ gắn khi đã xác nhận không thể tải/truy cập full-text; không gắn khi chỉ thiếu abstract.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "EC-N",
      label: "Không có thực nghiệm (Vision / Tutorial / Position)",
      description: "Loại bài báo lý thuyết, vision paper, tutorial không có đánh giá thực nghiệm.",
      kind: "exclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: ["tutorial", "vision paper", "position paper", "panel discussion"],
        matchMode: "any",
        fields: ["title"],
      },
    },
    {
      id: "EC-O",
      label: "Chủ đề ngoài phạm vi (Out of Scope)",
      description:
        "Loại bỏ: UI/DOM testing, internal unit test (JUnit/class-level), pure fault localization, phi phần mềm.",
      kind: "exclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "swt302_ep_bva",
      parameters: { checkOutOfScope: true },
    },
  ],
  schemaVersion: "2.0.0",
  profileVersion: 1,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

export const PRESET_GENERIC: ResearchProfile = {
  id: "preset_generic",
  name: "Generic Literature Review",
  description:
    "Hồ sơ nghiên cứu tổng quan tài liệu khoa học tổng quát. Người dùng tự định nghĩa chủ đề, câu hỏi nghiên cứu và tiêu chí mà không bị ràng buộc bởi luật SWT302.",
  researchQuestions: ["Tổng quan tình hình nghiên cứu hiện tại và các hướng tiếp cận chính trong chủ đề nghiên cứu."],
  reviewType: "literature_review",
  searchStrings: [
    {
      id: "generic_str_1",
      name: "Truy vấn chính",
      query: "",
      isDefault: true,
    },
  ],
  yearRange: {
    enabled: false,
  },
  languageRequirements: ["English", "en"],
  allowedPublicationTypes: ["conference", "journal", "proceedings", "book_chapter"],
  targetIncludedCount: 20,
  sourcePolicies: {
    google_scholar: { prismaRole: "primary" },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "primary" },
    semantic_scholar: { prismaRole: "primary" },
  },
  criteria: [
    {
      id: "GEN-IC-PUB",
      label: "Công bố học thuật hợp lệ",
      description: "Bài báo xuất bản trên hội nghị, tạp chí hoặc chương sách được bình duyệt (peer-reviewed).",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["conference", "journal", "proceedings", "book_chapter"],
        rejectTheses: true,
      },
    },
    {
      id: "GEN-IC-LANG",
      label: "Ngôn ngữ bài viết",
      description: "Văn bản viết bằng tiếng Anh (hoặc ngôn ngữ được định nghĩa).",
      kind: "inclusion",
      required: false,
      stage: "metadata",
      evaluator: "language",
      parameters: { allowedLanguages: ["English", "en"] },
    },
    {
      id: "GEN-EC-DUP",
      label: "Trùng lặp bài viết (Duplicate)",
      description: "Loại bài trùng DOI hoặc trùng tiêu đề đã xác nhận.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "GEN-EC-ACC",
      label: "Không thể truy cập toàn văn",
      description: "Chỉ loại khi đã xác nhận không thể lấy được toàn văn bài báo.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "GEN-IC-REL",
      label: "Phù hợp mục tiêu nghiên cứu (Relevance)",
      description: "Tiêu đề và tóm tắt phù hợp với phạm vi câu hỏi nghiên cứu đã đề ra.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "manual_assessment",
      parameters: { prompt: "Xác nhận bài viết có liên quan trực tiếp đến câu hỏi nghiên cứu." },
    },
  ],
  schemaVersion: "2.0.0",
  profileVersion: 1,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

export const PRESET_VISUALLY_IMPAIRED_AAC: ResearchProfile = {
  id: "preset_visually_impaired_aac",
  name: "Giao tiếp tử tế & Sự tự tin của trẻ khiếm thị",
  description:
    "Nghiên cứu tìm hiểu mối liên hệ giữa giao tiếp tử tế (X), cảm nhận được hỗ trợ (M) và sự tự tin (Y) của trẻ em khiếm thị trong môi trường giáo dục (The Role of Kind and Supportive Communication in Supporting Self-Confidence among Children with Visual Impairments in Educational Settings).",
  researchQuestions: [
    "RQ1: Trẻ em khiếm thị cảm nhận giao tiếp tử tế như thế nào?",
    "RQ2: Giao tiếp tử tế có liên hệ với cảm nhận được hỗ trợ của trẻ không?",
    "RQ3: Giao tiếp tử tế và cảm nhận được hỗ trợ có liên hệ với sự tự tin của trẻ không?",
    "RQ4: Giáo viên và bạn bè có thể điều chỉnh cách giao tiếp ra sao để hỗ trợ trẻ?",
  ],
  reviewType: "systematic_review",
  searchStrings: [
    {
      id: "vi_str_11_combined",
      name: "Chuỗi tổng hợp (Combined Core)",
      query:
        '("children with visual impairments" OR "visually impaired children" OR "blind children") AND ("supportive communication" OR "teacher support" OR "peer support" OR "social support") AND ("self-confidence" OR "self-esteem" OR "self-efficacy")',
      isDefault: true,
      source: "google_scholar",
    },
    {
      id: "vi_str_1_y_focus",
      name: "1. Đối tượng và sự tự tin (Y focus)",
      query: '"children with visual impairments" "self-confidence"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_2_psych_ext",
      name: "2. Mở rộng tài liệu tâm lý (Self-esteem)",
      query: '"visually impaired children" "self-esteem"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_3_comm_sup",
      name: "3. Giao tiếp hỗ trợ (X focus)",
      query: '"visual impairment" "supportive communication"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_4_teacher_sup",
      name: "4. Hỗ trợ từ giáo viên",
      query: '"students with visual impairments" "teacher support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_5_peer_sup",
      name: "5. Hỗ trợ từ bạn bè",
      query: '"visually impaired children" "peer support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_6_med_m",
      name: "6. Biến trung gian (Perceived social support)",
      query: '"visual impairment" "perceived social support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_7_rel_m_y",
      name: "7. Liên hệ M–Y (Social support & Self-esteem)",
      query: '"visual impairment" "social support" "self-esteem"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_8_scale_y",
      name: "8. Thang đo Y (Self-confidence scale)",
      query: '"children" "self-confidence" "scale"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_9_scale_m",
      name: "9. Thang đo M (Social support scale)",
      query: '"children" "perceived social support" "scale"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_10_mediation",
      name: "10. Phân tích trung gian (Mediation model)",
      query: '"visual impairment" "social support" "mediation"',
      isDefault: false,
      source: "google_scholar",
    },
  ],
  yearRange: {
    start: 2010,
    end: 2026,
    enabled: true,
  },
  languageRequirements: ["English", "Vietnamese", "en", "vi"],
  allowedPublicationTypes: ["journal", "review", "conference", "proceedings", "book_chapter"],
  targetIncludedCount: 30,
  sourcePolicies: {
    google_scholar: {
      prismaRole: "primary",
      notes: "Được tính vào nguồn tìm kiếm ứng viên của nghiên cứu này.",
    },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "supplementary" },
    semantic_scholar: { prismaRole: "primary" },
  },
  criteria: [
    {
      id: "IC-01",
      label: "Thuộc nhóm trực tiếp, bổ trợ hoặc lý thuyết nền",
      description:
        "Bài viết đóng góp cho biến X (giao tiếp tử tế), M (cảm nhận hỗ trợ), Y (sự tự tin) hoặc quan hệ H1-H4 trong mô hình.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "supportive communication",
          "kind communication",
          "positive communication",
          "empathetic communication",
          "compassionate communication",
          "teacher support",
          "peer support",
          "social support",
          "perceived social support",
          "emotional support",
          "self-confidence",
          "confidence",
          "self-esteem",
          "self-efficacy",
          "self-concept",
          "giao tiếp tử tế",
          "giao tiếp hỗ trợ",
          "sự tự tin",
          "hỗ trợ xã hội",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
      evidenceRequirements: "Phải xuất hiện từ khóa về giao tiếp, hỗ trợ xã hội hoặc sự tự tin/khái niệm bổ trợ.",
    },
    {
      id: "IC-02",
      label: "Đối tượng và bối cảnh phù hợp",
      description:
        "Đối tượng là trẻ em/học sinh khiếm thị hoặc bối cảnh giáo dục học đường (hoặc bài lý thuyết nền phù hợp).",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "children with visual impairments",
          "visually impaired children",
          "blind children",
          "students with visual impairments",
          "visual impairment",
          "visually impaired",
          "blind",
          "blindness",
          "low vision",
          "inclusive education",
          "special education",
          "school",
          "classroom",
          "educational setting",
          "trẻ khiếm thị",
          "học sinh khiếm thị",
          "khiếm thị",
          "giáo dục hòa nhập",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
    },
    {
      id: "IC-03",
      label: "Thông tin xuất bản đủ để xác minh và trích dẫn APA 7",
      description: "Bài viết có tác giả, năm xuất bản, tên venue và DOI/URL để định dạng danh mục tài liệu tham khảo.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["journal", "review", "conference", "proceedings", "book_chapter", "article"],
        rejectTheses: true,
        rejectPreprints: false,
      },
    },
    {
      id: "IC-04",
      label: "Truy cập được toàn văn",
      description: "Có thể tải hoặc đọc toàn văn bài báo để phục vụ thẩm định chuyên sâu.",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "IC-05",
      label: "Nội dung, phương pháp hoặc lập luận đủ rõ",
      description: "Bài báo có thiết kế nghiên cứu, thang đo hoặc cơ sở lý luận rõ ràng để đóng góp cho mô hình.",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "manual_assessment",
      parameters: {
        prompt: "Xác nhận bài báo có phương pháp đo lường hoặc cơ sở lý luận đóng góp cho X, M, Y hoặc H1-H4.",
      },
    },
    {
      id: "IC-06",
      label: "Đạt điều kiện độ dài (nếu được kích hoạt)",
      description: "Số trang tối thiểu (chỉ áp dụng khi người dùng bật yêu cầu độ dài từ 16 trang).",
      kind: "inclusion",
      required: false,
      stage: "full_text",
      evaluator: "page_count",
      parameters: { minPages: 16 },
    },
    {
      id: "EC-01",
      label: "Bài trùng lặp (Duplicate)",
      description: "Trùng mã DOI hoặc trùng tiêu đề đã được xác nhận với bài báo khác.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "EC-02",
      label: "Không liên quan đến đề tài hoặc cơ sở lý thuyết",
      description: "Không chứa bất kỳ nội dung nào về giao tiếp, hỗ trợ xã hội, sự tự tin hoặc trẻ em khiếm thị.",
      kind: "exclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "manual_assessment",
      parameters: { prompt: "Loại trừ nếu hoàn toàn lạc đề so với mô hình nghiên cứu." },
    },
    {
      id: "EC-03",
      label: "Không thuộc loại tài liệu được chấp nhận",
      description: "Loại trừ sách tóm tắt hội thảo, bài viết tạp chí thương mại, blog không bình duyệt.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: { rejectTheses: true },
    },
    {
      id: "EC-04",
      label: "Metadata mâu thuẫn chưa giải quyết",
      description: "Thông tin tác giả, năm, venue mâu thuẫn nghiêm trọng giữa các nguồn mà không thể xác minh.",
      kind: "exclusion",
      required: false,
      stage: "metadata",
      evaluator: "manual_assessment",
    },
    {
      id: "EC-05",
      label: "Không thể truy cập toàn văn sau các lần thử",
      description: "Đã thử qua nhiều nguồn (Publisher, arXiv, ResearchGate, Tab) nhưng không thể lấy toàn văn.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "EC-06",
      label: "Vi phạm điều kiện bắt buộc đã bật",
      description:
        "Vi phạm các tiêu chuẩn bắt buộc do người nghiên cứu kích hoạt (ví dụ độ dài tối thiểu nếu được chốt).",
      kind: "exclusion",
      required: false,
      stage: "full_text",
      evaluator: "manual_assessment",
    },
  ],
  schemaVersion: "2.0.0",
  profileVersion: 1,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

export const BUILTIN_PRESETS: ResearchProfile[] = [PRESET_SWT302, PRESET_GENERIC, PRESET_VISUALLY_IMPAIRED_AAC];
