import { ResearchProfile } from "./types";

export const SCHEMA_VERSION = "2.0.0";

/**
 * 1. Preset SWT302: REST API Testing EP/BVA (Giữ nguyên toàn bộ chính sách & luật hiện tại)
 */
export const PRESET_SWT302: ResearchProfile = {
  id: "preset_swt302",
  name: "SWT302 REST API EP/BVA",
  description:
    "Nghiên cứu sinh ca kiểm thử tự động cho REST API bằng Phân hoạch tương đương (EP) và Phân tích giá trị biên (BVA) theo chuẩn RBL môn SWT302.",
  researchQuestions: [
    "RQ FA26-EXT-12: Kỹ thuật kiểm thử black-box nào dựa trên EP và BVA cho tham số HTTP request của REST API?",
    "Các nghiên cứu thực nghiệm định lượng kết quả phát hiện lỗi / coverage như thế nào trong Table/Figure?",
  ],
  reviewType: "systematic_review",
  searchStrings: [
    {
      id: "swt302_str_a",
      name: "String A (Chính thức theo protocol)",
      query:
        '("REST API testing" OR "natural language requirement" OR "RESTestBench") AND ("equivalence partitioning" OR "boundary-value analysis" OR "boundary testing") AND ("fault detection" OR "mutant detection" OR "bugs found")',
      isDefault: true,
      source: "google_scholar",
    },
    {
      id: "swt302_str_b",
      name: "String B (Dự phòng mở rộng)",
      query:
        '("REST API" OR "RESTful") AND ("black-box testing" OR "boundary value" OR "equivalence partition") AND ("automated testing" OR "test generation")',
      isDefault: false,
      source: "google_scholar",
    },
  ],
  yearRange: {
    start: 2020,
    end: 2026,
    enabled: true,
  },
  languageRequirements: ["English", "en"],
  allowedPublicationTypes: ["conference", "journal", "proceedings"],
  minPageCount: 4,
  targetIncludedCount: 15, // Mục tiêu số lượng paper đưa vào tổng quan (không phải quota API)
  sourcePolicies: {
    google_scholar: {
      prismaRole: "supplementary",
      notes:
        "Nguồn Google Scholar chỉ là paper ứng viên bổ trợ, không tính trực tiếp vào Identification của sơ đồ PRISMA chính thống.",
    },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "supplementary" },
    semantic_scholar: { prismaRole: "supplementary" },
  },
  criteria: [
    {
      id: "IC-L",
      label: "Ngôn ngữ tiếng Anh",
      description: "Paper viết bằng tiếng Anh và có bằng chứng văn bản.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "language",
      parameters: { allowedLanguages: ["English", "en"] },
    },
    {
      id: "IC-T",
      label: "Hội nghị / Tạp chí khoa học",
      description: "Đăng trên conference hoặc journal khoa học (loại trừ thesis, dissertation, blog).",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["conference", "journal", "proceedings", "symposium", "workshop"],
        rejectTheses: true,
        rejectPreprints: false, // Cho phép preprint nếu có venue được xác minh
      },
    },
    {
      id: "IC-Y",
      label: "Năm xuất bản 2020 - 2026",
      description: "Xuất bản trong khung năm 2020 đến 2026 theo protocol SWT302.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "year_range",
      parameters: { startYear: 2020, endYear: 2026 },
    },
    {
      id: "IC-P",
      label: "Kiểm thử REST API mức HTTP request",
      description:
        "Kiểm thử ở mức request cho dịch vụ HTTP (yêu cầu NL và/hoặc schema API: OpenAPI, Swagger, RAML). GraphQL riêng lẻ không đạt.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "swt302_ep_bva",
      parameters: { checkScope: "rest_api" },
    },
    {
      id: "IC-I",
      label: "Kỹ thuật EP và/hoặc BVA cho tham số request",
      description:
        "Kỹ thuật thiết kế test black-box: Phân hoạch tương đương (EP) và/hoặc Phân tích giá trị biên (BVA) cho tham số request.",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "swt302_ep_bva",
      parameters: { checkTechnique: "ep_bva" },
      evidenceRequirements: "Cần trích dẫn đoạn văn bản mô tả phương pháp EP/BVA cho tham số request (trang, mục).",
    },
    {
      id: "IC-E",
      label: "Kết quả thực nghiệm định lượng trong Table/Figure",
      description:
        "Có ít nhất 1 con số kết quả thực nghiệm trong Table hoặc Figure (không chỉ nhắc metric trong text).",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "swt302_ep_bva",
      parameters: { checkEmpirical: "table_or_figure" },
      evidenceRequirements: "Cần số liệu định lượng (%, số lỗi, coverage...) gắn liền với Table hoặc Figure.",
    },
    {
      id: "EC-D",
      label: "Trùng lặp với bài báo đã có (Duplicate)",
      description: "Trùng khóa chính DOI hoặc trùng tiêu đề đã xác nhận.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "EC-S",
      label: "Dưới 4 trang (Short paper / Poster)",
      description: "Loại bài báo dưới 4 trang khi đã xác minh số trang từ toàn văn.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "page_count",
      parameters: { minPages: 4 },
    },
    {
      id: "EC-A",
      label: "Không thể truy cập toàn văn (Unreachable full-text)",
      description: "Chỉ gắn khi đã xác nhận không thể tải/truy cập full-text; không gắn khi chỉ thiếu abstract.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "EC-N",
      label: "Không có thực nghiệm (Vision / Tutorial / Position)",
      description: "Loại bài báo lý thuyết, vision paper, tutorial không có đánh giá thực nghiệm.",
      kind: "exclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: ["tutorial", "vision paper", "position paper", "panel discussion"],
        matchMode: "any",
        fields: ["title"],
      },
    },
    {
      id: "EC-O",
      label: "Chủ đề ngoài phạm vi (Out of Scope)",
      description:
        "Loại bỏ: UI/DOM testing, internal unit test (JUnit/class-level), pure fault localization, phi phần mềm.",
      kind: "exclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "swt302_ep_bva",
      parameters: { checkOutOfScope: true },
    },
  ],
  schemaVersion: SCHEMA_VERSION,
  profileVersion: 1,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

/**
 * 2. Preset Generic: Generic Literature Review (Không ép REST API, năm, thực nghiệm hay độ dài)
 */
export const PRESET_GENERIC: ResearchProfile = {
  id: "preset_generic",
  name: "Generic Literature Review",
  description:
    "Hồ sơ nghiên cứu tổng quan tài liệu khoa học tổng quát. Người dùng tự định nghĩa chủ đề, câu hỏi nghiên cứu và tiêu chí mà không bị ràng buộc bởi luật SWT302.",
  researchQuestions: ["Tổng quan tình hình nghiên cứu hiện tại và các hướng tiếp cận chính trong chủ đề nghiên cứu."],
  reviewType: "literature_review",
  searchStrings: [
    {
      id: "generic_str_1",
      name: "Truy vấn chính",
      query: "",
      isDefault: true,
    },
  ],
  yearRange: {
    enabled: false,
  },
  languageRequirements: ["English", "en"],
  allowedPublicationTypes: ["conference", "journal", "proceedings", "book_chapter"],
  targetIncludedCount: 20,
  sourcePolicies: {
    google_scholar: { prismaRole: "primary" },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "primary" },
    semantic_scholar: { prismaRole: "primary" },
  },
  criteria: [
    {
      id: "GEN-IC-PUB",
      label: "Công bố học thuật hợp lệ",
      description: "Bài báo xuất bản trên hội nghị, tạp chí hoặc chương sách được bình duyệt (peer-reviewed).",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["conference", "journal", "proceedings", "book_chapter"],
        rejectTheses: true,
      },
    },
    {
      id: "GEN-IC-LANG",
      label: "Ngôn ngữ bài viết",
      description: "Văn bản viết bằng tiếng Anh (hoặc ngôn ngữ được định nghĩa).",
      kind: "inclusion",
      required: false,
      stage: "metadata",
      evaluator: "language",
      parameters: { allowedLanguages: ["English", "en"] },
    },
    {
      id: "GEN-EC-DUP",
      label: "Trùng lặp bài viết (Duplicate)",
      description: "Loại bài trùng DOI hoặc trùng tiêu đề đã xác nhận.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "GEN-EC-ACC",
      label: "Không thể truy cập toàn văn",
      description: "Chỉ loại khi đã xác nhận không thể lấy được toàn văn bài báo.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "GEN-IC-REL",
      label: "Phù hợp mục tiêu nghiên cứu (Relevance)",
      description: "Tiêu đề và tóm tắt phù hợp với phạm vi câu hỏi nghiên cứu đã đề ra.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "manual_assessment",
      parameters: { prompt: "Xác nhận bài viết có liên quan trực tiếp đến câu hỏi nghiên cứu." },
    },
  ],
  schemaVersion: SCHEMA_VERSION,
  profileVersion: 1,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

/**
 * 3. Preset Đề tài: Vai trò của giao tiếp tử tế trong việc hỗ trợ sự tự tin của trẻ em khiếm thị trong môi trường giáo dục
 * (The Role of Kind and Supportive Communication in Supporting Self-Confidence among Children with Visual Impairments in Educational Settings)
 * Mô hình nghiên cứu: X (Giao tiếp tử tế) -> M (Cảm nhận được hỗ trợ) -> Y (Sự tự tin). Giả thuyết H1, H2, H3, H4.
 */
export const PRESET_VISUALLY_IMPAIRED_AAC: ResearchProfile = {
  id: "preset_visually_impaired_aac",
  name: "Giao tiếp tử tế & Sự tự tin của trẻ khiếm thị",
  description:
    "Nghiên cứu tìm hiểu mối liên hệ giữa giao tiếp tử tế (X), cảm nhận được hỗ trợ (M) và sự tự tin (Y) của trẻ em khiếm thị trong môi trường giáo dục (The Role of Kind and Supportive Communication in Supporting Self-Confidence among Children with Visual Impairments in Educational Settings).",
  researchQuestions: [
    "RQ1: Trẻ em khiếm thị cảm nhận giao tiếp tử tế như thế nào?",
    "RQ2: Giao tiếp tử tế có liên hệ với cảm nhận được hỗ trợ của trẻ không?",
    "RQ3: Giao tiếp tử tế và cảm nhận được hỗ trợ có liên hệ với sự tự tin của trẻ không?",
    "RQ4: Giáo viên và bạn bè có thể điều chỉnh cách giao tiếp ra sao để hỗ trợ trẻ?",
  ],
  reviewType: "systematic_review",
  searchStrings: [
    {
      id: "vi_str_11_combined",
      name: "Chuỗi tổng hợp (Combined Core)",
      query:
        '("children with visual impairments" OR "visually impaired children" OR "blind children") AND ("supportive communication" OR "teacher support" OR "peer support" OR "social support") AND ("self-confidence" OR "self-esteem" OR "self-efficacy")',
      isDefault: true,
      source: "google_scholar",
    },
    {
      id: "vi_str_1_y_focus",
      name: "1. Đối tượng và sự tự tin (Y focus)",
      query: '"children with visual impairments" "self-confidence"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_2_psych_ext",
      name: "2. Mở rộng tài liệu tâm lý (Self-esteem)",
      query: '"visually impaired children" "self-esteem"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_3_comm_sup",
      name: "3. Giao tiếp hỗ trợ (X focus)",
      query: '"visual impairment" "supportive communication"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_4_teacher_sup",
      name: "4. Hỗ trợ từ giáo viên",
      query: '"students with visual impairments" "teacher support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_5_peer_sup",
      name: "5. Hỗ trợ từ bạn bè",
      query: '"visually impaired children" "peer support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_6_med_m",
      name: "6. Biến trung gian (Perceived social support)",
      query: '"visual impairment" "perceived social support"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_7_rel_m_y",
      name: "7. Liên hệ M–Y (Social support & Self-esteem)",
      query: '"visual impairment" "social support" "self-esteem"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_8_scale_y",
      name: "8. Thang đo Y (Self-confidence scale)",
      query: '"children" "self-confidence" "scale"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_9_scale_m",
      name: "9. Thang đo M (Social support scale)",
      query: '"children" "perceived social support" "scale"',
      isDefault: false,
      source: "google_scholar",
    },
    {
      id: "vi_str_10_mediation",
      name: "10. Phân tích trung gian (Mediation model)",
      query: '"visual impairment" "social support" "mediation"',
      isDefault: false,
      source: "google_scholar",
    },
  ],
  yearRange: {
    start: 2010,
    end: 2026,
    enabled: true,
  },
  languageRequirements: ["English", "Vietnamese", "en", "vi"],
  allowedPublicationTypes: ["journal", "review", "conference", "proceedings", "book_chapter"],
  targetIncludedCount: 30, // Mục tiêu 30 articles theo yêu cầu chuẩn
  sourcePolicies: {
    google_scholar: {
      prismaRole: "primary",
      notes: "Được tính vào nguồn tìm kiếm ứng viên của nghiên cứu này.",
    },
    openalex: { prismaRole: "primary" },
    arxiv: { prismaRole: "supplementary" },
    semantic_scholar: { prismaRole: "primary" },
  },
  criteria: [
    {
      id: "VI-IC-COMM",
      label: "Giao tiếp tử tế và hỗ trợ (Supportive & Kind Communication - Biến X)",
      description:
        "Tập trung vào cách giáo viên và bạn bè lắng nghe, tôn trọng, đồng cảm, khuyến khích và giao tiếp tử tế với trẻ (Biến độc lập X trong mô hình).",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "supportive communication",
          "kind communication",
          "positive communication",
          "empathetic communication",
          "compassionate communication",
          "respectful communication",
          "teacher support",
          "teacher encouragement",
          "teacher-student interaction",
          "peer support",
          "peer interaction",
          "social support",
          "perceived social support",
          "emotional support",
          "active listening",
          "constructive feedback",
          "compassion",
          "encouragement",
          "caring",
          "friendly communication",
          "giao tiếp tử tế",
          "giao tiếp hỗ trợ",
          "thấu cảm",
          "đồng cảm",
          "lắng nghe",
          "động viên",
          "khích lệ",
          "tôn trọng",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
      evidenceRequirements: "Phải có bằng chứng về giao tiếp tử tế, hỗ trợ từ giáo viên/bạn bè hoặc tương tác học đường.",
    },
    {
      id: "VI-IC-POP",
      label: "Đối tượng trẻ em / học sinh khiếm thị (Children with Visual Impairment)",
      description:
        "Đối tượng nghiên cứu là trẻ em, học sinh, thanh thiếu niên khiếm thị / nhìn kém / mù trong độ tuổi học đường K-12.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "children with visual impairments",
          "visually impaired children",
          "blind children",
          "students with visual impairments",
          "blind students",
          "low vision children",
          "pediatric visual impairment",
          "pupils with visual impairments",
          "young visually impaired",
          "visually impaired youth",
          "blind youth",
          "inclusive education",
          "special education",
          "school",
          "classroom",
          "educational setting",
          "trẻ khiếm thị",
          "học sinh khiếm thị",
          "trẻ em khiếm thị",
          "trẻ mù",
          "giáo dục hòa nhập",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
    },
    {
      id: "VI-IC-CONF",
      label: "Sự tự tin và năng lực tâm lý (Self-Confidence - Biến kết quả Y)",
      description:
        "Đo lường hoặc phân tích sự tự tin (Self-confidence), lòng tự trọng (Self-esteem), năng lực tự thân hoặc sự hòa nhập của trẻ.",
      kind: "inclusion",
      required: true,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "self-confidence",
          "confidence",
          "self-esteem",
          "self-efficacy",
          "autonomy",
          "social participation",
          "self-concept",
          "psychological well-being",
          "sự tự tin",
          "tự tin",
          "lòng tự trọng",
          "tự chủ",
          "hòa nhập xã hội",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
    },
    {
      id: "VI-IC-AAC-SUP",
      label: "Công nghệ trợ giúp & AAC (Nhóm bổ trợ, KHÔNG bắt buộc)",
      description:
        "Các công cụ giao tiếp tăng cường (AAC), màn hình nổi Braille, tactile, thiết bị hỗ trợ. Đây là nhóm bổ trợ, không bắt buộc bài báo phải có.",
      kind: "inclusion",
      required: false, // BỔ TRỢ: Không bắt buộc bài báo phải dùng công nghệ
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: [
          "augmentative and alternative communication",
          "aac",
          "assistive technology",
          "tactile",
          "braille",
          "screen reader",
          "haptic",
          "công nghệ trợ giúp",
        ],
        matchMode: "any",
        fields: ["title", "abstract", "snippet", "keywords"],
      },
    },
    {
      id: "VI-IC-PUB",
      label: "Thông tin xuất bản đủ chuẩn trích dẫn APA 7",
      description: "Bài viết có tác giả, năm, tên tạp chí/hội nghị chuẩn và liên kết DOI/URL xác thực.",
      kind: "inclusion",
      required: true,
      stage: "metadata",
      evaluator: "publication_type",
      parameters: {
        allowedTypes: ["journal", "review", "conference", "proceedings", "book_chapter", "article"],
        rejectTheses: true,
        rejectPreprints: false,
      },
    },
    {
      id: "VI-IC-FULLTEXT",
      label: "Truy cập được toàn văn bài báo",
      description: "Bài báo có thể đọc hoặc tải toàn văn để thẩm định phương pháp và trích xuất bằng chứng chuyên sâu.",
      kind: "inclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
    {
      id: "VI-EC-RETRACTED",
      label: "Bài báo bị rút lại (Retracted Article)",
      description: "Tuyệt đối loại trừ các bài báo đã bị tòa soạn rút lại (Retracted).",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "keyword_group",
      parameters: {
        keywords: ["retracted", "retraction"],
        matchMode: "any",
        fields: ["title", "abstract"],
      },
    },
    {
      id: "VI-EC-DUP",
      label: "Trùng lặp bài viết (Duplicate)",
      description: "Trùng mã DOI hoặc trùng tiêu đề đã được xác nhận với bài báo khác.",
      kind: "exclusion",
      required: true,
      stage: "metadata",
      evaluator: "duplicate",
      parameters: { checkDoi: true, checkTitle: true },
    },
    {
      id: "VI-EC-ADULT",
      label: "Nghiên cứu thuần về sinh viên đại học / người cao tuổi (Không có trẻ em)",
      description: "Loại bài chỉ khảo sát người trưởng thành hoặc sinh viên đại học mà không liên quan đến trẻ em K-12.",
      kind: "exclusion",
      required: false,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: ["university students", "higher education", "college students", "undergraduate students", "older adults", "elderly"],
        matchMode: "any",
        fields: ["title"],
      },
    },
    {
      id: "VI-EC-MED",
      label: "Can thiệp y khoa/phẫu thuật thuần túy",
      description: "Loại bài thuần về quy trình phẫu thuật nhãn khoa, thử nghiệm lâm sàng thuốc không có yếu tố giao tiếp hay giáo dục.",
      kind: "exclusion",
      required: false,
      stage: "title_abstract",
      evaluator: "keyword_group",
      parameters: {
        keywords: ["cataract surgery", "intraocular lens", "corneal surgery", "retinopathy of prematurity clinical trial", "pharmacokinetics"],
        matchMode: "any",
        fields: ["title"],
      },
    },
    {
      id: "VI-EC-ACC",
      label: "Không thể truy cập toàn văn sau các lần thử",
      description: "Đã thử qua nhiều nguồn (Publisher, arXiv, ResearchGate, Tab) nhưng không thể lấy toàn văn.",
      kind: "exclusion",
      required: true,
      stage: "full_text",
      evaluator: "full_text_availability",
      parameters: { requireFullText: true },
    },
  ],
  schemaVersion: SCHEMA_VERSION,
  profileVersion: 2,
  createdAt: "2026-10-05T00:00:00.000Z",
  updatedAt: "2026-10-05T00:00:00.000Z",
};

export const BUILTIN_PRESETS: ResearchProfile[] = [PRESET_SWT302, PRESET_GENERIC, PRESET_VISUALLY_IMPAIRED_AAC];
